---
kind: ConfigMap
apiVersion: v1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  name: acs-sync-init-bundle-script
  namespace: stackrox
data:
  script.sh: |-
    #!/bin/bash
    echo -n "[1/3] Waiting for ACS Central to be ready..."
    while [[ $(curl -s -k -o /dev/null -w "%{http_code}" $ROX_CENTRAL_ADDRESS) -ne 200 ]]; do echo -n "." && sleep 1; done; echo -n -e " [ONLINE]\n"
    echo ""

    echo "[2/3] Retrieving the Init Bundle..."
    roxctl --insecure-skip-tls-verify \
      -e $ROX_CENTRAL_ADDRESS -p $ACS_ADMIN_PASSWORD \
      central init-bundles generate $ACS_SECURED_CLUSTER \
      --output-secrets cluster_init_bundle.yaml
    echo ""

    echo "[3/3] Applying the init Bundle secrets to the local cluster..."
    oc apply -f cluster_init_bundle.yaml
