---
kind: ConfigMap
apiVersion: v1
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  name: acs-fetch-vuln-definitions-script
  namespace: stackrox
data:
  # This script was taken from https://github.com/stackrox/contributions/blob/main/util-scripts/cronjob-upload-vuln-definitions/upload-vulns-configmap.yaml
  script.sh: |-
    #!/bin/bash
    echo -n "[1/3] Waiting for ACS Central to be ready..."
    while [[ $(curl -s -k -o /dev/null -w "%{http_code}" $ROX_CENTRAL_ADDRESS) -ne 200 ]]; do echo -n "." && sleep 1; done; echo -n -e " [ONLINE]\n"

    echo "[2/3] Retrieving the Scanner Vulnerability Updates..."
    curl https://install.stackrox.io/scanner/scanner-vuln-updates.zip --output /tmp/scanner-vuln-updates.zip

    echo "[3/3] Uploading vulnerabilities to Central..."
    roxctl scanner upload-db --insecure-skip-tls-verify \
      -e $ROX_CENTRAL_ADDRESS \
      -p $ACS_ADMIN_PASSWORD \
      --scanner-db-file=/tmp/scanner-vuln-updates.zip
