---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "11"
  name: acs-fetch-vuln-definitions
  namespace: stackrox
spec:
  template:
    spec:
      containers:
      - name: acs-fetch-vuln-definitions
        image: quay.io/alopezme/rhacs-roxctl-oc:4.3.4
        imagePullPolicy: Always
        command:
        - /opt/script.sh
        env:
        - name: ACS_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: central-htpasswd
              key: password
        - name: ROX_CENTRAL_ADDRESS
          value: "https://central.stackrox.svc:443"
        volumeMounts: 
        - name: scripts
          mountPath: /opt
      volumes:
      - name: scripts
        configMap:
          name: acs-fetch-vuln-definitions-script
          defaultMode: 0555
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccountName: default
      terminationGracePeriodSeconds: 30
