---
apiVersion: project.openshift.io/v1
kind: Project
metadata:
  annotations:
    openshift.io/description: This project contains all the resources related to
      the ACS operator
    openshift.io/display-name: ACS Operator
    argocd.argoproj.io/sync-wave: "00"
  name: rhacs-operator
