---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: rhacs
  name: rhacs
  namespace: gitops
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: openshift
    repoURL: https://github.com/alvarolop/ocp-acs
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions: []